name: cicd

on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - main
      - dev

jobs:
  build-test-linux:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    container:
      image: 'ghcr.io/monamimani-builds/cpp-devcontainer:latest'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            configure-preset: "Linux-Clang-Ninja-Debug"
            build-preset: "Linux-Clang-Ninja-Debug"
          - os: ubuntu-latest
            configure-preset: "Linux-Clang-Ninja-Release"
            build-preset: "Linux-Clang-Ninja-Release"

    name: ${{matrix.build-preset}}
    steps:
      - uses: actions/checkout@v4
  
      - name: Env variable
        shell: bash
        run: |
          printenv
          # echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV
  
      - name: Set ownership
        shell: bash
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          #chown -R $(id -u):$(id -g) $PWD
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
  
      - name: Vcpkg Cache
        uses: ./.github/actions/vcpkg_cache
  
      - name: CPM Cache
        id: cache-cpm
        uses: actions/cache@v4
        with:
          path: _Out/cpm_sources
          key: ${{ runner.os }}-cpm-${{ hashFiles('_Out/cpm_sources/**/') }}
          restore-keys: |
            ${{ runner.os }}-cpm-
  
      - name: "[Linux] CMake Configure & Build"
        if: runner.os == 'Linux'
        run: |
  
          cmake --preset ${{matrix.configure-preset}} -DGIT_SHA:STRING=${{ github.sha }} -DPersonalWorks_ENABLE_CLANG_TIDY=OFF -DPersonalWorks_ENABLE_CPPCHECK=OFF
          cmake --build --preset ${{matrix.build-preset}}
